Repository ergebnis/phpstan-rules, pull requests merged in 2021-11, with the labels that each got.

#381 Bump support for PHPStan to version 1.0
  CHANGELOG.md
  composer-require-checker.json
  composer.json
  composer.lock
  phpstan-baseline.neon
  phpstan.neon
  src/Classes/FinalRule.php
  src/Classes/PHPUnit/Framework/TestCaseWithSuffixRule.php
  src/Methods/NoParameterWithContainerTypeDeclarationRule.php
  test/Integration/Classes/PHPUnit/Framework/TestCaseWithSuffixRuleTest.php
  test/Integration/Methods/NoParameterWithContainerTypeDeclarationRuleTest.php
Labels: enhancement, dependency

#386 Fix: Use `--generate-baseline` option for generating baseline for `phpstan/phpstan`
  Makefile
  phpstan-baseline.neon
Labels: bug

#385 Enhancement: Update `vimeo/psalm`
  composer.json
  composer.lock
  psalm-baseline.xml
Labels: enhancement

#387 Fix: Do not bother caching cache files for `phpstan/phpstan` and `vimeo/psalm`
  .github/workflows/integrate.yaml
Labels: bug

#388 Fix: Split condition
  src/Classes/FinalRule.php
Labels: bug

#390 Fix: Wrapping
  src/Classes/FinalRule.php
  src/Classes/NoExtendsRule.php
  src/Classes/PHPUnit/Framework/TestCaseWithSuffixRule.php
  src/Closures/NoNullableReturnTypeDeclarationRule.php
  src/Closures/NoParameterWithNullDefaultValueRule.php
  src/Closures/NoParameterWithNullableTypeDeclarationRule.php
  src/Expressions/NoCompactRule.php
  src/Expressions/NoEmptyRule.php
  src/Expressions/NoErrorSuppressionRule.php
  src/Expressions/NoEvalRule.php
  src/Expressions/NoIssetRule.php
  src/Files/DeclareStrictTypesRule.php
  src/Functions/NoNullableReturnTypeDeclarationRule.php
  src/Functions/NoParameterWithNullDefaultValueRule.php
  src/Functions/NoParameterWithNullableTypeDeclarationRule.php
  src/Methods/FinalInAbstractClassRule.php
  src/Methods/NoConstructorParameterWithDefaultValueRule.php
  src/Methods/NoNullableReturnTypeDeclarationRule.php
  src/Methods/NoParameterWithContainerTypeDeclarationRule.php
  src/Methods/NoParameterWithNullDefaultValueRule.php
  src/Methods/NoParameterWithNullableTypeDeclarationRule.php
  src/Methods/PrivateInFinalClassRule.php
  src/Statements/NoSwitchRule.php
Labels: bug

#391 Fix: Use `Xdebug` instead of `pcov` for collecting code coverage
  .github/CONTRIBUTING.md
  .github/workflows/integrate.yaml
Labels: bug

#392 Fix: Split condition
  .github/workflows/integrate.yaml
  Makefile
  src/Functions/NoNullableReturnTypeDeclarationRule.php
Labels: bug

#358 Fix: Run `friendsofphp/php-cs-fixer` on fixtures
  .github/workflows/integrate.yaml
  .php-cs-fixer.fixture.php
  Makefile
Labels: bug

#323 Enhancement: Run tests on PHP 8.0
  .github/settings.yml
  .github/workflows/integrate.yaml
Labels: enhancement, stale

#393 Fix: DocBlocks
  psalm-baseline.xml
  src/Classes/FinalRule.php
  src/Classes/PHPUnit/Framework/TestCaseWithSuffixRule.php
Labels: bug

#394 Fix: Avoid comparing boolean with boolean
  psalm-baseline.xml
  src/Classes/FinalRule.php
Labels: bug

#395 Fix: Adjust `Classes\FinalRule` to inspect attributes
  .github/workflows/integrate.yaml
  CHANGELOG.md
  Makefile
  README.md
  composer.json
  composer.lock
  psalm-baseline.xml
  src/Classes/FinalRule.php
  test/Fixture/Classes/FinalRuleWithAttributes/Failure/NonFinalClassWithUnqualifiedDoctrineOrmMappingEntityAttribute.php
  test/Fixture/Classes/FinalRuleWithAttributes/Failure/NonFinalClassWithUnqualifiedEntityAttribute.php
  test/Fixture/Classes/FinalRuleWithAttributes/Failure/NonFinalClassWithUnqualifiedOrmEntityAttribute.php
  test/Fixture/Classes/FinalRuleWithAttributes/Failure/NonFinalClassWithUnqualifiedOrmMappingEntityAttribute.php
  test/Fixture/Classes/FinalRuleWithAttributes/Success/NonFinalClassWithAliasedOrmEntityAttribute.php
  test/Fixture/Classes/FinalRuleWithAttributes/Success/NonFinalClassWithQualifiedDoctrineOrmMappingEntityAttribute.php
  test/Fixture/Classes/FinalRuleWithAttributes/Success/NonFinalClassWithQualifiedEntityAttribute.php
  test/Fixture/Classes/FinalRuleWithAttributes/Success/NonFinalClassWithQualifiedMappingEntityAttribute.php
  test/Fixture/Classes/FinalRuleWithAttributes/Success/NonFinalClassWithQualifiedOrmMappingEntityAttribute.php
  test/Integration/Classes/FinalRuleWithAttributesTest.php
Labels: bug
